version: 2
updates:
  # Proiectul principal (Rădăcină)
  - package-ecosystem: "npm" # Lasă exact "npm". GitHub recunoaște automat fișierul yarn.lock cu această setare.
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies" # Pune automat eticheta pe PR
    commit-message:
      prefix: "fix"    # Prefix util pentru a apărea corect în Changelog la următorul Release automat

  # Proiectul Server (Folder /server)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "fix"
